name: Assign PR to Project

on:
  pull_request:
    types: [opened, labeled]

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign PR to One Project
    steps:
    - name: Assign NEW pull requests to public project
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/bn3101group7/projects/3'
